# Exported from Render on 2024-11-04T17:52:09Z
services:
- type: web
  name: cdea-finance
  runtime: ruby
  repo: https://github.com/matinou-github/cdea-finance.git
  branch: main
  plan: free
  envVars:
  - key: RAILS_MASTER_KEY
    sync: false
  region: oregon
  buildCommand: bundle install; bundle exec rails assets:precompile; bundle exec rails assets:clean; ./bin/render-build.sh; ./bin/rails db:migrate; 
  startCommand: ./bin/rails server
version: "1"
