default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: matinou2
  password: matinou2
  host: localhost

development:
  <<: *default
  database: cdea_finance_development

test:
  <<: *default
  database: cdea_finance_test

production:
  <<: *default
  database: cdea_finance_production
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
